### PR TITLE
terraform: basic Prometheus alerting rules

### PR DESCRIPTION
**Pull request by tgeoghegan**
Configures the Prometheus Helm chart to include alerting rules defined
in a standalone YAML file. Updates `prometheus-alertmanager`
configuration so that only alerts with `severity: page` are routed to
the Victorops receiver.

We now have the following alerts set up:

 - page if any `workflow-manager` instance has not run in the last 30
   minutes
 - page if more than 95% of intake tasks fail during the last hour
 - page if more than 95% of aggregate tasks fail during the last 8 hours
 - page if any PubSub queue has undelivered messages for an entire hour

### CODE REVIEW

**Review by aaomidi — APPROVED** [review]

**Comment by aaomidi** [comment]
Just to double check, do we have code that only deploys this on prod/staging?

**Comment by tgeoghegan** [comment]
Good question! The alerts get deployed everywhere, but `prometheus-alertmanager` is not hooked up to Victorops in all environments. So outside of prod, alerts will be tracked in `alertmanager`, but only in prod will they generate pages. We will have to get more sophisticated here, though, because while I want to get alerts from staging, I don't want them to buzz someone's phone at night. I think the thing to do will be to introduce an environment label on alerts so we can define different alert routing rules which resolve to different receivers with different urgencies. But right now, I want to get any alerting in prod at all.

**Comment by tgeoghegan** [comment]
I went and created a `prio-staging` routing key in VictorOps (we already had a `prio-prod-us` one). In this latest commit, I configure `prod-us.tfvars` and `staging-{facil,pha}.tfvars` to send alerts to their corresponding VO routing keys. `prio-prod-us` is hooked up to an escalation policy that pages; `prio-staging` is hooked up to one that emails and sends a message to a slack channel.

**Review by aaomidi — APPROVED** [review]

**Comment by tgeoghegan** [comment]
While testing in dev, I found a problem with the `prometheus-alertmanager` config: I amended the alert routing so that only `severity: page` alerts go to VictorOps, but that means there's nowhere to send other alerts. I'm going to set up a default alert route that emails or slacks us. While I'm re-opening this PR, I'm also going to add an alert for dead letter queue subscription depth, so we can catch undelivered messages.

**Pull request merged**
